name: lein_test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['src/**','test/**', 'project.clj']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths: ['src/**','test/**', 'project.clj']

jobs:
  run-lein-tests:
    name: lein test - Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.4
        with:
          cli: latest              # Clojure CLI based on tools.deps
          lein: latest                  # Leiningen
          boot: latest                  # Boot.clj
          bb: latest                    # Babashka
          clj-kondo: latest        # Clj-kondo
          cljstyle: latest             # cljstyle
          zprint: latest                # zprint
      - name: Run lein tests with dev test profile
        run: lein with-profile dev test
      - name: Run lein tests with fips profile
        run: lein with-profile fips test
